name: Sync Asgaros RSS to GitHub and Telegram

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

       - name: Mirror feed from site into repo
      env:
        SRC: ${{ secrets.ASGAROS_FEED_URL_SITE }} # 你的站点RSS，如 https://myvirtual.free.nf/index.php?af_asgaros_topics=1
      run: |
        mkdir -p public
        curl -fsSL -A "Mozilla/5.0" "$SRC" -o public/asgaros.xml
        echo "Fetched $(wc -c < public/asgaros.xml) bytes"

      - name: Run sync
      env:
        FEED_URL: public/asgaros.xml
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python scripts/rss_to_md_and_tg.py

      - name: Inspect filesystem (debug)
        run: |
          ls -la
          ls -la data || true
          ls -la posts || true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add posts data || true
          git commit -m "chore: sync Asgaros RSS" || echo "No changes"
          git push
