name: Sync Asgaros RSS to GitHub and Telegram

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install feedparser requests

      - name: Mirror feed from site into repo
        env:
          SRC: ${{ secrets.ASGAROS_FEED_URL_SITE }} # e.g. https://myvirtual.free.nf/index.php?af_asgaros_topics=1
        run: |
          set -e
          mkdir -p public
          if [ -z "${SRC:-}" ]; then echo "ASGAROS_FEED_URL_SITE is empty"; exit 1; fi
          SRC_CLEAN="$(printf %s "$SRC" | tr -d '\r' | sed -e 's/&amp;/\&/g' -e 's/&#038;/\&/g' -e 's/ /%20/g')"
          echo "Fetching feed..."
          curl -v --fail --location -A "Mozilla/5.0" "$SRC_CLEAN" -o public/asgaros.xml
          echo "Fetched $(wc -c < public/asgaros.xml) bytes"
          if [ ! -s public/asgaros.xml ]; then echo "Downloaded feed is empty"; exit 1; fi

      - name: Show feed head (debug)
        run: |
          head -n 40 public/asgaros.xml | sed -e 's/[^[:print:]\t]//g' | cat

      - name: Run sync
        env:
          FEED_URL: public/asgaros.xml
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # DISABLE_TELEGRAM: "1"      # optional: disable Telegram during testing
          # DEBUG_TOUCH_ON_EMPTY: "1"  # optional: create data/last_run.txt if no new entries
        run: |
          python scripts/rss_to_md_and_tg.py

      - name: Inspect filesystem (debug)
        run: |
          ls -la
          ls -la data || true
          ls -la posts || true
          ls -la public || true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add posts data public || true
          git commit -m "chore: sync Asgaros RSS" || echo "No changes"
          git push
